name: belatuk_oauth1
version: 3.0.0
description: "\"RFC 5849: The OAuth 1.0 Protocol\" client implementation for Dart."
homepage: https://github.com/nbspou/dart-oauth1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.0
  http: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.0.0
